### ISSUE TITLE
Compact generic transforms

### ISSUE THREAD

**Issue by koczkatamas** [koczkatamas/onelang#25]
Add an option to describe the transformation in the following form:

```yaml
 - input: $object[$elementExpr] = $newValue
   output: $object.set($elementExpr, $newValue)
```

which will do the same as now this:

```yaml
  - description: "$object[$elementExpr] = $newValue -> $object.set($elementExpr, $newValue)"
    input:
      exprKind: Binary
      operator: =
      left:
        exprKind: ElementAccess
        object: $object
        elementExpr: $elementExpr
      right: $newValue
    output:
      exprKind: Call
      method:
        exprKind: PropertyAccess
        object: $object
        propertyName: set
      arguments: [$elementExpr, $newValue]
```
